# Generated by Django 2.2.28 on 2022-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_title_img',
            field=models.TextField(default='/public/contestimgs/default.png'),
        ),
    ]