# Generated by Django 2.2.28 on 2022-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='byte_length',
            field=models.IntegerField(null=True),
        ),
    ]