# Generated by Django 2.1.7 on 2022-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180501_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_token_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
