# Generated by Django 2.1.7 on 2022-05-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_token_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accepted_of_all_submission_number',
            field=models.IntegerField(default=0),
        ),
    ]
