# Generated by Django 2.1.7 on 2022-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220308_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_of_all_submission_number',
            field=models.IntegerField(default=0),
        ),
    ]
