# Generated by Django 2.2.28 on 2022-11-21 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_position',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
    ]