# Generated by Django 2.2.28 on 2022-11-25 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20221121_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedUserList',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='managed_lists', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manged_user_list',
                'ordering': ('-last_update_time',),
            },
        ),
    ]