# Generated by Django 2.2.28 on 2022-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment_content',
            field=models.TextField(null=True),
        ),
    ]