# Generated by Django 2.2.28 on 2022-11-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_notification_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]