# Generated by Django 2.2.28 on 2023-07-04 09:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(null=True)),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('title', models.CharField(max_length=40, null=True)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codereview.Code')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codereview',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='CodeReviewNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.DateTimeField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.TextField()),
                ('target_username', models.TextField()),
                ('action_username', models.TextField()),
                ('notificationtype', models.TextField()),
                ('content', models.TextField()),
                ('comment_content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('line_num', models.IntegerField(default=-1, null=True)),
                ('avatar', models.TextField(default='/public/avatar/default.png')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codereview.CodeReview')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
