# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        working-directory: ${{ env.working-directory }}
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: npm install
      run: npm ci
      working-directory: ${{ env.working-directory }}
    - name: set node env
      run: export NODE_ENV=development 
      working-directory: ${{ env.working-directory }}
    - name: set npm dll
      run: npm run build:dll
      working-directory: ${{ env.working-directory }}
    - name: build
      run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
      
