# Generated by Django 2.2.28 on 2023-01-06 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0017_problemrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0011_contest_contest_title_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCode',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('checksum', models.TextField(default=utils.shortcuts.rand_str)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('language', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'draftcode',
            },
        ),
    ]