# Generated by Django 2.2.28 on 2023-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcode',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]